---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: wego-github-podinfo-deploy
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: wego-github-podinfo-deploy
  url: ssh://git@github.com/ozamosi/podinfo-deploy.git

